### ISSUE TITLE
Write script to create properties to represent datasets in Wikidata

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/datamart#114]
We need to create the following properties to represent datasets in Wikidata:

```

C2001:
  label: datamart identifier
  description: identifier of a dataset in the Datamart system
  datatype: MonolingualText
  P31: Q19847637
  P1629: Q1172284

C2004:
  label: keywords
  description: keywords associated with an item to facilitate finding the item using text search
  datatype: StringValue
  P31: Q18616576

C2005:
  label: variable measured
  description: the variables measured in a dataset
  datatype: StringValue
  P31: Q18616576
  P1628: http://schema.org/variableMeasured

C2006:
  label: values
  description: the values of a variable represented as a text document
  datatype: StringValue
  P31: Q18616576

C2007:
  label: data type
  description: the data type used to represent the values of a variable, integer (Q729138), Boolean (Q520777), Real (Q4385701), String (Q184754), Categorical (Q2285707)
  datatype: Item
  P31: Q18616576

C2008:
  label: semantic type
  description: a URL that identifies the semantic type of a variable in a dataset
  datatype: URL
  P31: Q18616576
```
