### ISSUE TITLE
Create example dataset in our Blazegraph

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/datamart#115]
The dataset would be modeled roughly like the following:

```
D1000001:
  label: Table 10 ...
  description: ...
  P31: Q1172284
  P2699: http://...
  C2001: D1000001
  C2004: "whatever text we can put here to match the keywords in the query"
  C2005: County # variable measured
    C2007: string # data type
    C2008: http://schema.org/city #semantic type
    C2006: "Autauga Balwdwin ..." # text
    P1545: 0 # column index
  C2005: Violent Crime
    C2007: integer
    C2008: ??? # semantic type always required?
    C2006: ??? # maybe for numeric we don't store the values
    P1545: 1
  C2005: County_wikidata_0
    C2007: string
    C2008: http://wikidata.org/Q???
    C2006: "Q1234, Q2345, ..."
    P1545: 9
```
